---
- name: Update default Nginx configuration
  ansible.builtin.lineinfile:
    path: /etc/nginx/conf.d/default.conf
    regexp: '^    (listen\s+){{ nginx_port }};$'
    line: '    listen localhost:{{ nginx_port }};'

- name: Configure reverse proxy
  ansible.builtin.template:
    src: templates/proxy.conf.j2
    dest: /etc/nginx/conf.d/proxy.conf
  notify: Restart Nginx

- name: Restart Nginx
  ansible.builtin.meta: flush_handlers