---
nginx_repository: |
  deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] 
  https://nginx.org/packages/mainline/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} nginx
nginx_port: 8080
nginx_custom_html_dir: /tmp/index
ansible_dir_html: /home/vagrant/files
owner_index: vagrant
group_index: vagrant
ansible_dir: /home/vagrant/
nginx_proxy_port: 80